apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-htlvoujh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-htlvoujh:037449363237bddeab5ee0ca4af57a0afcd76caf@sha256:badfcb0228e25b5520218e2aa421cf032761245013b6fd092dc2f97bcae2ed3d
          name: container-image
